export let FETCH_INGREDIENTS_PENDING = 'FETCH_INGREDIENTS_PENDING';
export let FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export let FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
// Burger Actions
export const CHANGE_ING_COUNT = 'CHANGE_ING_COUNT';
export let SET_ORDERED = 'SET_ORDERED';
